export const Images = {
    Welcome: require('./Images/welcome.png'),
    Login: require('./Images/login.jpeg'),
    Clothes: require('./Images/clothes.png'),
    Shoes: require('./Images/shoes.png'),
    Accessories: require('./Images/accessories.png'),
    HomeAppliances: require('./Images/homeAppliance.png'),
    Furniture: require('./Images/furniture.png'),
    HomeAccessories: require('./Images/homeAccessories.png'),
    Toys: require('./Images/toys.png'),
    Garden: require('./Images/garden.png'),
    BabyProducts: require('./Images/babyProducts.png'),
    Books: require('./Images/books.png'),
    School: require('./Images/school.png'),
    Handmade: require('./Images/handmade.png'),
    Auto: require('./Images/auto.png'),
    Sports: require('./Images/sports.png'),
    Music: require('./Images/Music.png'),
    AddImage: require('./Images/addImage.png')
};
